export const ALL_PERMISSIONS = [
  'ADMINISTRATOR',
  'MANAGE_ROLES',
  'KICK_MEMBERS',
  'CREATE_INVITE',
  'MANAGE_SERVER',
  'MANAGE_STICKERS',
  'MANAGE_WEBHOOKS',
  'MANAGE_CHANNEL',
  'SEND_MESSAGES',
  'MANAGE_MESSAGES',
  'ADD_REACTIONS',
  'ATTACH_FILES',
  'MENTION_EVERYONE',
] as const;

export type Permission = typeof ALL_PERMISSIONS[number];

export const SERVER_PERMISSIONS: Permission[] = [
  'ADMINISTRATOR',
  'MANAGE_ROLES',
  'KICK_MEMBERS',
  'CREATE_INVITE',
  'MANAGE_SERVER',
  'MANAGE_STICKERS',
  'MANAGE_WEBHOOKS',
];

export const CHANNEL_PERMISSIONS: Permission[] = [
  'MANAGE_CHANNEL',
  'SEND_MESSAGES',
  'MANAGE_MESSAGES',
  'ADD_REACTIONS',
  'ATTACH_FILES',
  'MENTION_EVERYONE',
];

export const DM_PERMISSIONS: Permission[] = [
  'SEND_MESSAGES',
  'ADD_REACTIONS',
  'ATTACH_FILES',
];
