FROM dxflrs/garage:v2.1.0 AS garage

FROM alpine:3.20
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
# RUN sed -i 's/#http/http/g' /etc/apk/repositories
# RUN apk update
RUN apk add --no-cache ca-certificates

COPY --from=garage /garage /usr/local/bin/garage
