import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [{type: 'autogenerated', dirName: 'guide'}],
  sdk: [
    {
      type: 'category',
      label: '核心 API',
      items: [
        'core-api/index',
        'core-api/rest-api',
        'core-api/websocket-api',
        'core-api/data-structures',
      ],
    },
    {
      type: 'category',
      label: 'Bot 开发',
      items: [
        'bot-sdk/index',
        'bot-sdk/core-concepts',
        'bot-sdk/fetcher-bot-golang',
        'bot-sdk/interactive-bot-python',
        'bot-sdk/best-practices',
      ],
    },
  ],
};

export default sidebars;
