import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Use docs root metadata instead of `docs/index.md`.
// Docusaurus uses this file for category metadata when autogenerating sidebars,
// and we also consume it here to keep the landing page configuration in one place.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const docsRootCategory = require('./docs/_category_.json') as {
  label: string;
  link?: { type: 'generated-index'; title?: string; description?: string; slug?: string };
};

// eslint-disable-next-line @typescript-eslint/no-require-imports
const coreApiCategory = require('./docs/core-api/_category_.json') as {
  label: string;
  link?: { type: 'generated-index'; title?: string; description?: string; slug?: string };
};

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: docsRootCategory.label,
      collapsible: false,
      link: docsRootCategory.link,
      items: [
        {
          type: 'category',
          label: '开始',
          items: ['start/introduction', 'start/getting-started'],
        },
        {
          type: 'category',
          label: '平台',
          items: [
            'platform/platform-design',
            'platform/backend-guide',
            'platform/frontend-guide',
            {
              type: 'category',
              label: coreApiCategory.label,
              link: coreApiCategory.link,
              items: [{type: 'autogenerated', dirName: 'core-api'}],
            },
          ],
        },
        {
          type: 'category',
          label: 'Bot 生态',
          items: [
            'bot-sdk/bot-ecosystem',
            {
              type: 'category',
              label: 'Bot SDK',
              items: [
                'bot-sdk/index',
                'bot-sdk/core-concepts',
                'bot-sdk/fetcher-bot-golang',
                'bot-sdk/interactive-bot-python',
                'bot-sdk/best-practices',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '参考',
          items: ['reference/references', 'reference/infrastructure-setup'],
        },
      ],
    },
  ],
};

export default sidebars;
