export const ALL_PERMISSIONS = [
  // Server-Level Permissions
  'ADMINISTRATOR',
  'MANAGE_ROLES',
  'KICK_MEMBERS',
  'BAN_MEMBERS',
  'CREATE_INVITE',
  'CREATE_INSTANT_INVITE',
  'MANAGE_SERVER',
  'MANAGE_WEBHOOKS',
  'MANAGE_CHANNELS',
  'CHANGE_NICKNAME',
  'MANAGE_NICKNAMES',

  // Channel-Level Permissions
  'MANAGE_CHANNEL',
  'SEND_MESSAGES',
  'MANAGE_MESSAGES',
  'ADD_REACTIONS',
  'ATTACH_FILES',
  'MENTION_EVERYONE',
  'READ_MESSAGE_HISTORY',
  'EMBED_LINKS',
] as const;

export type Permission = typeof ALL_PERMISSIONS[number];
